- name: Setup Networking on the control-plane, compute and bastion nodes.
  hosts:
    - masters
    - workers
    - bastion
  roles:
    - setup-networking

- name: Install Runtime and Kubernetes
  hosts:
    - masters
    - workers
  roles:
    - runtime
    - download-k8s
    - install-k8s

- name: Install networking - calico
  hosts: masters
  roles:
    - role: install-calico
      when: cni_provider == "calico"

- name: Install networking - flannel
  hosts:
    - masters
    - workers
  roles:
    - role: install-flannel
      when: cni_provider == "flannel"
