[bastion]
163.68.77.237
[masters]
192.168.25.105
192.168.25.30
[workers]
192.168.25.174
192.168.25.112
192.168.25.114
[workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /root/basti/k8s-ansible/k8s-key -q root@150.240.127.86" -i /root/basti/k8s-ansible//k8s-key'
[masters:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /root/basti/k8s-ansible/k8s-key -q root@150.240.127.86" -i /root/basti/k8s-ansible//k8s-key'