[bastion]
<IP Address>

[masters]
169.48.19.202

[workers]
169.48.19.205
169.48.19.206

[workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i <path/to/private-key> -q root@<Bastion IP>" -i <path/to/private-key>'

[masters:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i <path/to/private-key> -q root@<Bastion IP>" -i <path/to/private-key>'
