---
- name: Add Redhat Subscription
  block:
    - name: check username and password are set
      fail:
        msg: "username and password are the mandatory values to execute the playbook for rhel"
      when:  ansible_distribution == "RedHat" and  username is not defined or password is not defined

    - name: Register RHEL
      shell: subscription-manager register --username {{ username }} --password {{ password }} --auto-attach
      when:  ansible_distribution == "RedHat"

- name: Forwarding IPv4 and letting iptables see bridged traffic
  block:
    - name: Loading Modules Boot Time
      copy:
        dest: "/etc/modules-load.d/k8s.conf"
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules First time
      modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - overlay
        - br_netfilter

    - name: Sysctl settings
      sysctl:
        name: "{{ item }}"
        sysctl_file: /etc/sysctl.d/k8s.conf
        value: 1
        state: present
        reload: yes
      with_items:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

- name: Common Prerequisites
  block:
    - name: Generate crictl.yaml
      template:
        src: crictl/crictl.yaml.j2
        dest: /etc/crictl.yaml
        mode: '0644'
    - name: Install crictl - {{ critools_version }}
      unarchive:
        src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ critools_version }}/crictl-{{ critools_version }}-linux-ppc64le.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes

    - name: Add Public Docker repository
      yum_repository:
        name: public-docker
        description: Public Docker Repository
        baseurl: https://download.docker.com/linux/centos/8/ppc64le/stable/
        gpgcheck: no

    - name: Install iptables
      yum:
        name: iptables

- name: Install and Configure Runtime - Docker
  import_tasks: docker.yaml
  when: runtime == "docker"

- name: Install and Configure Runtime - Containerd
  import_tasks: containerd.yaml
  when: runtime == "containerd"
