- name: Configure networks on bastion
  shell: |
    dev_uuid=$(grep $(ip a | grep {{ bastion_private_ip }} | awk '{ print $NF }') <(nmcli -g device,uuid con) | cut -d':' -f2)
    nmcli connection modify $dev_uuid ipv4.addresses {{ bastion_private_cidr }} ipv4.gateway {{ bastion_private_gateway }}
    nmcli connection modify $dev_uuid +ipv4.routes "{{ private_cidr }} {{ bastion_private_gateway }}"
    nmcli connection modify $dev_uuid -ipv4.gateway ""
    nmcli connection up $dev_uuid
  when: node_type == "bastion"

- name: Copy the ip-forwarder.sh script
  copy:
    src: ip-forwarder.sh
    dest: /root
    mode: '0744'
  when: node_type == "bastion"

- name: Setup forwarding rules through ip-forwarder.sh on bastion
  shell: |
    public_interface=$(ip a | grep {{ bastion_internal_ip }} | awk '{print $NF}')
    private_interface=$(ip a | grep {{ bastion_private_ip }} | awk '{print $NF}')
   ./root/ip-forwarder.sh $private_interface $public_interface
  when: node_type == "bastion"

- name: Identify interfaces on the masters and workers associated with private IP
  shell: |
    dev_uuid=$(grep $(ip a | grep {{ ansible_default_ipv4.address }} | awk '{ print $NF }') <(nmcli -g device,uuid con) | cut -d':' -f2)
    nmcli conn modify $dev_uuid ipv4.gateway "{{ bastion_internal_ip }}"
    nmcli conn modify $dev_uuid +ipv4.routes "{{ private_cidr }} {{ bastion_private_gateway }}"
    nmcli conn up $dev_uuid

  when: node_type == "master" or node_type == "worker"